#!/bin/bash
# sae-island oracle — v4.9.3 contract around the SynthSAEBench-16k engine.
#
# Differences from the v3-era run.sh:
#   - workspace contract: trains the AGENT's sae.py + train_config.yaml
#     (engine.py is staged into the workspace so `import sae` resolves there)
#   - async submit/collect: training runs under nohup; this script waits up to
#     ORACLE_WAIT (default 480s) and otherwise returns STILL_TRAINING — call
#     again to collect. No worker bash call ever needs to exceed 10 minutes.
#   - GPU-lock timeouts and engine crashes produce a visible RESULT_ERROR,
#     NEVER a logged 0.0 row (the v3 lock logged fake zeros on timeout).
#   - results.tsv is chmod-444; only this script appends (chmod dance).
#
# Usage: bash run.sh <name> "description"     (CLAUDE_AGENT_ID set by harness)
# Env:   SAE_SMOKE=1  → 200k-sample training, mechanics tests only.
#        ORACLE_WAIT  → seconds to wait inline before STILL_TRAINING (default 90 —
#                       short on purpose: agent bash tools kill the PROCESS GROUP on
#                       timeout, so this call must return before any default timeout;
#                       the training itself survives via setsid)

AGENT="${CLAUDE_AGENT_ID:-agent0}"
NAME="${1:-exp}"
DESC="${2:-no description}"
DIR="$(cd "$(dirname "$0")" && pwd)"
WS="$DIR/workspace/$AGENT"
PYTHON="${VENV_PYTHON:-$HOME/venv/bin/python3}"
[ -x "$PYTHON" ] || PYTHON=python3
WAIT_BUDGET="${ORACLE_WAIT:-90}"

if [ ! -f "$WS/sae.py" ]; then
    echo "ERROR: $WS/sae.py missing — edit your workspace copy, not the domain root" >&2
    exit 1
fi
cp "$DIR/engine.py" "$WS/engine.py"
[ -f "$WS/train_config.yaml" ] || cp "$DIR/train_config.yaml" "$WS/train_config.yaml"

CFG="$WS/train_config.yaml"
if [ -n "${SAE_SMOKE:-}" ]; then
    CFG="$WS/train_config_smoke.yaml"
    awk '$1=="training_samples:" {print "training_samples: 200000"; next} {print}' \
        "$WS/train_config.yaml" > "$CFG"
fi

echo "SOURCE: $WS/sae.py"

log_row() {  # $1=score $2=elapsed_seconds
    local N EXP
    N=$(awk 'NR>1' "$DIR/results.tsv" | wc -l | tr -d ' ')
    EXP=$(printf "EXP-%03d" $((N+1)))
    chmod 644 "$DIR/results.tsv"
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" "$EXP" "$1" "$2" "keep" "$DESC" "$AGENT" "$NAME" >> "$DIR/results.tsv"
    chmod 444 "$DIR/results.tsv"
    echo "SCORE: $1"
    echo "ELAPSED: ${2}s"
    echo "LOGGED: $EXP -> results.tsv"
}

collect() {
    if [ -f "$WS/RESULT_ERROR" ]; then
        echo "ORACLE ERROR (no row logged — fix and resubmit):" >&2
        cat "$WS/RESULT_ERROR" >&2
        mv "$WS/RESULT_ERROR" "$WS/RESULT_ERROR.$(date +%s)"
        return 2
    fi
    if [ -f "$WS/RESULT" ]; then
        local SCORE ELAPSED
        read -r SCORE ELAPSED < "$WS/RESULT"
        case "$SCORE" in
            ''|*[!0-9.]*) echo "ERROR: bad RESULT content: $(cat "$WS/RESULT")" >&2
                          mv "$WS/RESULT" "$WS/RESULT_ERROR.$(date +%s)"; return 2 ;;
        esac
        mv "$WS/RESULT" "$WS/RESULT.logged.$(date +%s)"
        log_row "$SCORE" "$ELAPSED"
        return 0
    fi
    return 1  # nothing to collect yet
}

# Collect any finished run first (idempotent — never double-logs)
collect; RC=$?
[ $RC -eq 0 ] && exit 0
[ $RC -eq 2 ] && exit 1

# Submit if nothing is running
if [ -f "$WS/TRAINING.pid" ] && kill -0 "$(cat "$WS/TRAINING.pid" 2>/dev/null)" 2>/dev/null; then
    echo "TRAINING IN PROGRESS (pid $(cat "$WS/TRAINING.pid")) — waiting up to ${WAIT_BUDGET}s"
else
    cat > "$WS/train_job.sh" <<JOB
#!/bin/bash
# generated by run.sh — one training job for $AGENT
LOCKFILE="/tmp/saebench-gpu.lock"
WHO="$AGENT-\$(basename "$DIR")"
waited=0
while ! (set -o noclobber; echo "\$WHO \$(date +%s)" > "\$LOCKFILE") 2>/dev/null; do
    started=\$(cut -d' ' -f2 "\$LOCKFILE" 2>/dev/null)
    age=\$(( \$(date +%s) - \${started:-0} ))
    [ "\$age" -gt 2400 ] && { rm -f "\$LOCKFILE"; continue; }   # break stale locks
    if [ "\$waited" -ge 3600 ]; then
        echo "gpu-lock-timeout after 3600s (holder: \$(cat "\$LOCKFILE" 2>/dev/null))" > "$WS/RESULT_ERROR"
        rm -f "$WS/TRAINING.pid"; exit 1
    fi
    sleep 15; waited=\$((waited+15))
done
T0=\$(date +%s)
cd "$WS" && OMP_NUM_THREADS=2 "$PYTHON" engine.py "$CFG" --matches 1 --seed 42 > "$WS/train.log" 2> "$WS/train.err"
RC=\$?
T1=\$(date +%s)
rm -f "\$LOCKFILE"
if [ \$RC -eq 0 ]; then
    SCORE=\$(tail -1 "$WS/train.log")
    case "\$SCORE" in
        ''|*[!0-9.]*) echo "engine-ok-but-no-score: '\$SCORE' (see train.log)" > "$WS/RESULT_ERROR" ;;
        *) echo "\$SCORE \$((T1-T0))" > "$WS/RESULT" ;;
    esac
else
    echo "engine-exit-\$RC (see train.err tail):" > "$WS/RESULT_ERROR"
    tail -5 "$WS/train.err" | tr '\r' '\n' | tail -5 >> "$WS/RESULT_ERROR"
fi
rm -f "$WS/TRAINING.pid"
JOB
    chmod +x "$WS/train_job.sh"
    # setsid: new session + process group — survives the caller's group-kill
    # (agent bash-tool timeouts SIGKILL the whole group; nohup alone is not enough)
    setsid nohup bash "$WS/train_job.sh" > /dev/null 2>&1 &
    echo $! > "$WS/TRAINING.pid"
    echo "SUBMITTED training for $AGENT (workspace sae.py + train_config.yaml)"
fi

# Inline wait: collect if it finishes within budget, else hand back
waited=0
while [ "$waited" -lt "$WAIT_BUDGET" ]; do
    sleep 10; waited=$((waited+10))
    collect; RC=$?
    [ $RC -eq 0 ] && exit 0
    [ $RC -eq 2 ] && exit 1
done
echo "STILL_TRAINING — run 'bash run.sh $NAME \"$DESC\"' again in a few minutes to collect the score."
exit 0
