#!/bin/bash
# generated by run.sh — one training job for agent0
LOCKFILE="/tmp/saebench-gpu.lock"
WHO="agent0-$(basename "/home/vincent/researchRalph/domains/sae-island-isl-a")"
waited=0
while ! (set -o noclobber; echo "$WHO $(date +%s)" > "$LOCKFILE") 2>/dev/null; do
    started=$(cut -d' ' -f2 "$LOCKFILE" 2>/dev/null)
    age=$(( $(date +%s) - ${started:-0} ))
    [ "$age" -gt 2400 ] && { rm -f "$LOCKFILE"; continue; }   # break stale locks
    if [ "$waited" -ge 3600 ]; then
        echo "gpu-lock-timeout after 3600s (holder: $(cat "$LOCKFILE" 2>/dev/null))" > "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/RESULT_ERROR"
        rm -f "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/TRAINING.pid"; exit 1
    fi
    sleep 15; waited=$((waited+15))
done
T0=$(date +%s)
cd "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0" && OMP_NUM_THREADS=2 "/home/vincent/venv/bin/python3" engine.py "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/train_config.yaml" --matches 1 --seed 42 > "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/train.log" 2> "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/train.err"
RC=$?
T1=$(date +%s)
rm -f "$LOCKFILE"
if [ $RC -eq 0 ]; then
    SCORE=$(tail -1 "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/train.log")
    case "$SCORE" in
        ''|*[!0-9.]*) echo "engine-ok-but-no-score: '$SCORE' (see train.log)" > "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/RESULT_ERROR" ;;
        *) echo "$SCORE $((T1-T0))" > "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/RESULT" ;;
    esac
else
    echo "engine-exit-$RC (see train.err tail):" > "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/RESULT_ERROR"
    tail -5 "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/train.err" | tr '\r' '\n' | tail -5 >> "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/RESULT_ERROR"
fi
rm -f "/home/vincent/researchRalph/domains/sae-island-isl-a/workspace/agent0/TRAINING.pid"
